;;; Bootstrap
;;; This file is generated by init.el at compile time.
;;;
;;; Copyright © 2015-2019 Fis Trivial <ybbs.daans@hotmail.com>
;;;
;;; This file is part of Foci-Emacs.
;;;
;;; Foci-Emacs is free software: you can redistribute it and/or modify
;;; it under the terms of the GNU General Public License as published by
;;; the Free Software Foundation, either version 3 of the License, or
;;; (at your option) any later version.
;;;
;;; Foci-Emacs is distributed in the hope that it will be useful,
;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with Foci-Emacs.  If not, see <http://www.gnu.org/licenses/>.
;;;

(load-file "~/.emacs.d/global-settings/archives-trivialfis.el")
(setq package-selected-package
      '(glsl-mode forge bbdb lsp-java lsp-mode cython-mode mu4e-alert ess ccls xterm-color yaml-mode cquery groovy-mode markdown-toc racket-mode ninja-mode cuda-mode helm-rtags flycheck-rtags company-rtags rtags lsp-ui matlab-mode paredit company-lsp lsp-python foci-org-dashboard nix-mode slime mu4e-jump-to-list sr-speedbar debbugs flycheck-haskell lsp-go sage-shell-mode meson-mode csv-mode slime-company cargo ox-gfm racer flycheck-rust cmake-ide rainbow-mode opencl-mode window-purpose helm-xref helm-gtags header2 geiser flyspell-correct-helm toc-org vala-mode flycheck-irony toml-mode rust-mode font-lock-studio langtool org-bullets company-irony company-irony-c-headers irony irony-eldoc projectile clang-format aggressive-indent disaster paradox org markdown-mode vline cmake-mode go-mode all-the-icons-dired company-math font-lock+ col-highlight winum powerline spacemacs-theme atom-dark-theme company-go highlight-symbol company-quickhelp company-auctex auctex company-c-headers srefactor company-php company-shell fill-column-indicator ecb elpy flycheck company undo-tree))
(package-install-selected-packages)

(load-file "~/.emacs.d/init.el")

;; Local Variables:
;; flycheck-disabled-checkers: (emacs-lisp-checkdoc emacs-lisp)
;; End:
